FROM tailscale/tailscale:latest as tailscale

FROM louislam/uptime-kuma:1

# Install Tailscale prerequisites
RUN apt-get update && apt-get install -y ca-certificates iptables
# Copy start up script
COPY ./start.sh /app/start.sh
# Copy Tailscale binaries from tailscale image
COPY --from=tailscale /usr/local/bin/tailscaled /app/tailscaled
COPY --from=tailscale /usr/local/bin/tailscale /app/tailscale
# Init Tailscale directories
RUN mkdir -p /var/run/tailscale /var/cache/tailscale /var/lib/tailscale

CMD ["/app/start.sh"]
